# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Identifying Paper Topics Evaluation"

providers:
  - id: google:gemini-1.5-flash
    config:
      temperature: 1.0
      maxOutputTokens: 1024

defaultTest:
  assert:
    - type: python
      value: file://metrics.py

prompts:
  - file://prompt_select_papers.txt

tests:
  - description: Evaluate accuracy of paper selection
    vars:
      topic: 
        - Machine Learning
        - Quantum Computing
        - Biotechnology
      papers: file://papers.json
    assert:
      - type: is-json