# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Identifying Paper Topics Evaluation"

providers:
  - id: google:gemini-1.5-flash
    config:
      temperature: 1.0
      maxOutputTokens: 1024

defaultTest:
  assert:
    - type: python
      value: file://metrics.py

prompts:
  - file://prompt_select_papers.txt

tests:
  - description: Evaluate paper relevance scoring for Machine Learning topic
    vars:
      topic: Machine Learning
      papers: file://papers.json
    assert:
      - type: is-json
  
  - description: Evaluate paper relevance scoring for Quantum Computing topic
    vars:
      topic: Quantum Computing
      papers: file://papers.json
    assert:
      - type: is-json

  - description: Evaluate paper relevance scoring for Biotechnology topic
    vars:
      topic: Biotechnology
      papers: file://papers.json
    assert:
      - type: is-json